# Generated by Django 2.1.3 on 2018-11-23 05:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('creation', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('EmployeeID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('technology', models.TextField()),
                ('usecase', models.TextField()),
                ('creation', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='Job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Register_App.Team'),
        ),
    ]
