# Generated by Django 2.1.3 on 2018-11-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='Job',
            new_name='Team',
        ),
    ]
