# Generated by Django 2.1.3 on 2018-11-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_App', '0002_auto_20181123_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='comment_text',
        ),
    ]
