# Generated by Django 2.1.3 on 2018-11-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_App', '0006_auto_20181123_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='technology',
        ),
        migrations.AddField(
            model_name='participants',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
