# Generated by Django 2.1.3 on 2018-11-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_App', '0008_auto_20181127_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
    ]
