# Generated by Django 2.1.3 on 2018-12-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_App', '0009_remove_team_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
